GestaoPedidosNotificacao.UI/Entities/Utilizador.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPedidosNotificacao.UI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizador()
        {
            this.Pedidos = new HashSet<Pedido>();
            this.PedidosHistoricoes = new HashSet<PedidosHistorico>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
        public string Funcao { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DataModificacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosHistorico> PedidosHistoricoes { get; set; }
    }
}

GestaoPedidosNotificacao.UI/Controllers/UtilizadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestaoPedidosNotificacao.UI.Entities;

namespace GestaoPedidosNotificacao.UI.Controllers
{
    public class UtilizadorsController : AppBaseController
    {
        private GestaoPedidosNotificacaoDBEntities db = new GestaoPedidosNotificacaoDBEntities();

        // GET: Utilizadors
        public ActionResult Index()
        {
            return View(db.Utilizadors.ToList());
        }

        // GET: Utilizadors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // GET: Utilizadors/Create
        public ActionResult Create()
        {
            FillListViewBag(null);
            return View();
        }

        // POST: Utilizadors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Senha,Email,Funcao,IsActive,RoleId")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                utilizador.DataModificacao = DateTime.Now;
                db.Utilizadors.Add(utilizador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            FillListViewBag(null);
            return View(utilizador);
        }

        // GET: Utilizadors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            FillListViewBag(utilizador);
            return View(utilizador);
        }

        // POST: Utilizadors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Senha,Email,Funcao,IsActive,RoleId")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                utilizador.DataModificacao = DateTime.Now;
                db.Entry(utilizador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            FillListViewBag(null);
            return View(utilizador);
        }

        // GET: Utilizadors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utilizador utilizador = db.Utilizadors.Find(id);
            db.Utilizadors.Remove(utilizador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        public void FillListViewBag(Utilizador utilizador)
        {
            var tipo = db.Roles.ToList();
            tipo.Insert(0, (new Role { Id = -1, Descricao = "Selecionar" }));

            if (utilizador == null)
            {
                ViewBag.RoleId = new SelectList(tipo, "Id", "Descricao");
            }
            else
            {
                ViewBag.RoleId = new SelectList(tipo, "Id", "Descricao", utilizador.RoleId);
             
            }
        }
    }
}

GestaoPedidosNotificacao.UI/Views/Utilizadors/Create.cshtml
@model GestaoPedidosNotificacao.UI.Entities.Utilizador

@{
    ViewBag.Title = "Cadastrar Utilizador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Funcao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Funcao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Funcao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5">
                <span>@Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "form-check-label" })</span>
                <span class="ml-5">@Html.CheckBox("IsActive", true, new { @class = "form-check-input" })</span>

                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })


            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

GestaoPedidosNotificacao.UI/Views/Utilizadors/Delete.cshtml
@model GestaoPedidosNotificacao.UI.Entities.Utilizador

@{
    ViewBag.Title = "Excluir utilizador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Tem certeza de que deseja excluir isso?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Funcao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Funcao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataModificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataModificacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestaoPedidosNotificacao.UI/Views/Utilizadors/Details.cshtml
@model GestaoPedidosNotificacao.UI.Entities.Utilizador

@{
    ViewBag.Title = "Utilizador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Funcao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Funcao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataModificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataModificacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class="btn btn-primary" }) |
    @Html.ActionLink("Voltar", "Index",null,new { @class="btn btn-danger" })
</p>

GestaoPedidosNotificacao.UI/Views/Utilizadors/Edit.cshtml
@model GestaoPedidosNotificacao.UI.Entities.Utilizador

@{
    ViewBag.Title = "Editar Utilizador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Funcao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Funcao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Funcao, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="col-md-4">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group mt-3">
            <div class="col-md-5">
                <span>@Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "form-check-label" })</span>
                <span class="ml-5">@Html.CheckBox("IsActive", Model.IsActive.Value , new { @class = "form-check-input" })</span>

                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })


            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

GestaoPedidosNotificacao.UI/Views/Utilizadors/Index.cshtml
@model IEnumerable<GestaoPedidosNotificacao.UI.Entities.Utilizador>

@{
    ViewBag.Title = "Utilizadores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mb-4">

    <div class="card-body">
        <span class="float-right">
            <br />
            @Html.ActionLink("Novo Utilizador", "Create", null, new { @class = "btn btn-primary" })
            <br />.
        </span>
        <table id="dataTable" class="table table-bordered dataTable" style="width:100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Funcao)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DataModificacao)
                    </th>
                    <th width="200"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Funcao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsActive)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataModificacao)
                        </td>
                        <td>
                            <a href="@Url.Action("Details","Utilizadors", new { id=item.Id })" class="btn btn-primary btn-circle">
                                <i class="fas fa-search"></i>
                            </a>
                            <a href="@Url.Action("Edit","Utilizadors", new { id=item.Id })" class="btn btn-success btn-circle">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="@Url.Action("Delete","Utilizadors", new { id=item.Id })" class="btn btn-danger btn-circle">
                                <i class="fas fa-trash"></i>
                            </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>