GestaoPedidosNotificacao.UI/Controllers/ServicoProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestaoPedidosNotificacao.UI.Entities;

namespace GestaoPedidosNotificacao.UI.Controllers
{
    public class ServicoProdutoesController : AppBaseController
    {
        private GestaoPedidosNotificacaoDBEntities db = new GestaoPedidosNotificacaoDBEntities();

        // GET: ServicoProdutoes
        public ActionResult Index()
        {
            return View(db.ServicoProdutoes.ToList());
        }

        // GET: ServicoProdutoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicoProduto servicoProduto = db.ServicoProdutoes.Find(id);
            if (servicoProduto == null)
            {
                return HttpNotFound();
            }
            return View(servicoProduto);
        }

        // GET: ServicoProdutoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServicoProdutoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Descricao,Quantidade,Valor,IsProduto")] ServicoProduto servicoProduto)
        {
            if (ModelState.IsValid)
            {
                servicoProduto.DataModificacao = DateTime.Now;
                db.ServicoProdutoes.Add(servicoProduto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(servicoProduto);
        }

        // GET: ServicoProdutoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicoProduto servicoProduto = db.ServicoProdutoes.Find(id);
            if (servicoProduto == null)
            {
                return HttpNotFound();
            }
            return View(servicoProduto);
        }

        // POST: ServicoProdutoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Descricao,Quantidade,Valor,IsProduto")] ServicoProduto servicoProduto)
        {
            if (ModelState.IsValid)
            {
                servicoProduto.DataModificacao = DateTime.Now;
                db.Entry(servicoProduto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(servicoProduto);
        }

        // GET: ServicoProdutoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicoProduto servicoProduto = db.ServicoProdutoes.Find(id);
            if (servicoProduto == null)
            {
                return HttpNotFound();
            }
            return View(servicoProduto);
        }

        // POST: ServicoProdutoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServicoProduto servicoProduto = db.ServicoProdutoes.Find(id);
            db.ServicoProdutoes.Remove(servicoProduto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestaoPedidosNotificacao.UI/Views/ServicoProdutoes/Create.cshtml
@model GestaoPedidosNotificacao.UI.Entities.ServicoProduto

@{
    ViewBag.Title = "Cadastrar Finalidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsProduto)
                    @Html.ValidationMessageFor(model => model.IsProduto, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

GestaoPedidosNotificacao.UI/Views/ServicoProdutoes/Delete.cshtml
@model GestaoPedidosNotificacao.UI.Entities.ServicoProduto

@{
    ViewBag.Title = "Excluir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Tem certeza de que deseja excluir isso?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataModificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataModificacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsProduto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsProduto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-primary" /> |
            @Html.ActionLink("Voltar", "Index",null, new { @class="btn btn-danger" })
        </div>
    }
</div>

GestaoPedidosNotificacao.UI/Views/ServicoProdutoes/Details.cshtml
@model GestaoPedidosNotificacao.UI.Entities.ServicoProduto

@{
    ViewBag.Title = "Finalidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataModificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataModificacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsProduto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsProduto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class="btn btn-primary" }) 
    @Html.ActionLink("Voltar", "Index",null, new { @class="btn btn-danger" })
</p>

GestaoPedidosNotificacao.UI/Views/ServicoProdutoes/Edit.cshtml
@model GestaoPedidosNotificacao.UI.Entities.ServicoProduto

@{
    ViewBag.Title = "Editar Finalidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.IsProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsProduto)
                    @Html.ValidationMessageFor(model => model.IsProduto, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Index", null, new { @class="btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
</div>

GestaoPedidosNotificacao.UI/Views/ServicoProdutoes/Index.cshtml
@model IEnumerable<GestaoPedidosNotificacao.UI.Entities.ServicoProduto>

@{
    ViewBag.Title = "Finalidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mb-4">

    <div class="card-body">
        <span class="float-right">
            <br />
            @Html.ActionLink("Novo Pedido", "Create", null, new { @class = "btn btn-primary" })
            <br />.
        </span>
        <table id="dataTable" class="table table-bordered dataTable" style="width:100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Quantidade)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Valor)
                    </th>
                    <th width="200"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantidade)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            <a href="@Url.Action("Details","ServicoProdutoes", new { id=item.Id })" class="btn btn-primary btn-circle">
                                <i class="fas fa-search"></i>
                            </a>
                            <a href="@Url.Action("Edit","ServicoProdutoes", new { id=item.Id })" class="btn btn-success btn-circle">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="@Url.Action("Delete","ServicoProdutoes", new { id=item.Id })" class="btn btn-danger btn-circle">
                                <i class="fas fa-trash"></i>
                            </a>


                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>