GestaoPedidosNotificacao.UI/Controllers/ContaController.cs
using GestaoPedidosNotificacao.UI.AppExceptions;
using GestaoPedidosNotificacao.UI.Entities;
using GestaoPedidosNotificacao.UI.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GestaoPedidosNotificacao.UI.Controllers
{
    public class ContaController : AppBaseController
    {
        private GestaoPedidosNotificacaoDBEntities db = new GestaoPedidosNotificacaoDBEntities();

        // GET: Conta
        public ActionResult Index()
        {
            return View();
        }

        [AppAllowUnauthorazed]
        [HttpGet]
        public ActionResult Login()
        {
            Session["UserName"] = null;
            Session["IsAutorizated"] = null;
            Session["Role"] = null;
            return View();
        }

        [AppAllowUnauthorazed]
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {

                    var logUsr = db.Utilizadors.FirstOrDefault(x => 
                        x.Email.ToLower() == model.UserName.ToLower() &&
                        x.Senha.Equals(model.Password) &&
                        x.IsActive == true
                    );

                    if (logUsr == null)
                        throw new AppUnautorizatedException();

                    FormsAuthentication.SetAuthCookie(logUsr.Id.ToString(), model.RememberMe);

                    if (logUsr.RoleId == null)
                        throw new AppUnautorizatedException();

                    Session["UserName"] = logUsr.Nome;
                    Session["IsAutorizated"] = true;
                    Session["Role"] = logUsr.Role.Descricao;

                    return RedirectToAction("Index","Home");
                }

                ModelState.AddModelError("", "Utilizador sem acesso!");
                return View();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
        [AppAuthorization]
        [HttpGet]
        public ActionResult Perfil()
        {

            var usr = db.Utilizadors.FirstOrDefault(x => x.Id == UserId);
            FillListViewBag(usr);
            return View(usr);
        }

        [ChildActionOnly]
        public ActionResult MudarMinhaSenha()
        {
            
            ChangePasswordModel model = new ChangePasswordModel();
            model.Id = UserId;
            
            return PartialView("MudarMinhaSenha", model);
        }

        [HttpPost]
        public ActionResult MudarMinhaSenhaPost(ChangePasswordModel userUpdating)
        {
            if (ModelState.IsValid)
            {
                var utilizador = db.Utilizadors.FirstOrDefault(x => x.Id == userUpdating.Id);
                utilizador.DataModificacao = DateTime.Now;
                utilizador.Senha = userUpdating.SenhaNova;

                db.Entry(utilizador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction(nameof(Perfil));
            }

            return RedirectToAction(nameof(Perfil));
        }


        public void FillListViewBag(Utilizador utilizador)
        {
            var tipo = db.Roles.ToList();
            tipo.Insert(0, (new Role { Id = -1, Descricao = "Selecionar" }));

            if (utilizador == null)
            {
                ViewBag.RoleId = new SelectList(tipo, "Id", "Descricao");
            }
            else
            {
                ViewBag.RoleId = new SelectList(tipo, "Id", "Descricao", utilizador.RoleId);

            }
        }
    }
}

GestaoPedidosNotificacao.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - Aldaware - Gestao Pedidos</title>
    @Scripts.Render("~/bundles/modernizr")
    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/Content/bootstrap-datepicker-1.9.0-dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <style>
        .alda-bg{
            background-color: #1b406e;
        }
    </style>

    
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        @Html.Partial("_Sidebar")
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                @Html.Partial("_TopbarNavbar")
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <p>&copy; @DateTime.Now.Year - ALDAWare Application</p>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    @Html.Partial("_LogoutModal")

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript-->
    
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->


    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/bootstrap-datepicker-1.9.0-dist/js/bootstrap-datepicker.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)

    <script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
            }
        });

        $("#DataEntidade").datepicker({
            format: 'dd/mm/yyyy'
        })
    });
    </script>
</body>
</html>

GestaoPedidosNotificacao.UI/Views/Shared/_LogoutModal.cshtml
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Deseja terminar sessão?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Selecione "Logout" abaixo se estiver pronto para encerrar sua sessão atual.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="@Url.Action("Login","Conta")">Logout</a>
            </div>
        </div>
    </div>
</div>
<!-- end Logout Modal-->

GestaoPedidosNotificacao.UI/Views/Shared/_Sidebar.cshtml
@{ 
    bool isAdmin = Session["Role"].ToString() == "Administrador";
    bool isUsuario = Session["Role"].ToString() == "Usuário";
    bool isRelatórios = Session["Role"].ToString() == "Relatórios";
}

<ul class="navbar-nav alda-bg sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
        <div class="sidebar-brand-icon">
            <img src="~/img/logo apd.png" style="width: 100%;"/>
        </div>
        @*<div class="sidebar-brand-text mx-3">GesPedidos<sup>alfa</sup></div>*@
    </a>
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Painel -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Home")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Painel</span>
        </a>
    </li>
    <!-- Divider -->
    
    <!-- Divider -->
    @*<hr class="sidebar-divider">*@
    <!-- Heading -->
    @*<div class="sidebar-heading">
        Addons
    </div>*@
    <!-- Nav Item - Pages Collapse Menu -->
    @*<li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
           aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse show" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item active" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>*@
    <!-- Nav Item - Charts -->
    @if (isAdmin || isUsuario)
    {
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Entidades")">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Entidades</span>
        </a>
    </li>    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Pedidoes")">
            <i class="fas fa-fw fa-table"></i>
            <span>Notificação</span>
        </a>
    </li>  
    }
    @if (isAdmin)
    {
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "ServicoProdutoes")">
            <i class="fas fa-fw fa-table"></i>
            <span>Finalidades</span>
        </a>
    </li>
    }
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRelatorios"
           aria-expanded="true" aria-controls="collapseRelatorios">
            <i class="fas fa-fw fa-file"></i>
            <span>Relatórios</span>
        </a>
        <div id="collapseRelatorios" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Relatórios:</h6>
                <a class="collapse-item" href="@Url.Action("EntidadesPageFiltro", "Relatorios")">Entidades</a>
                <a class="collapse-item" href="@Url.Action("NotificacoesPageFiltro", "Relatorios")">Notificações</a>
            </div>
        </div>
    </li>
    <!-- Divider -->
    @*<hr class="sidebar-divider">*@
    <!-- Heading -->

    @if (isAdmin)
    {

    <div class="sidebar-heading">
        Admin
    </div>
    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Configurações</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Configurações:</h6>
                <a class="collapse-item" href="@Url.Action("Index", "EntidadeTipoes")">Tipos de Entidades</a>
                <a class="collapse-item" href="@Url.Action("Index", "Status")">Status de Pedidos</a>
                <h6 class="collapse-header">Contas:</h6>
                <a class="collapse-item" href="@Url.Action("Index", "Utilizadors")">Utilizadores</a>
                <a class="collapse-item" href="@Url.Action("Create", "Utilizadors")">Novo Utilizador</a>
            </div>
        </div>
    </li>
    <hr class="sidebar-divider d-none d-md-block">
    }
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

GestaoPedidosNotificacao.UI/Views/Shared/_TopbarNavbar.cshtml
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search"
                               aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button" disabled>
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        


        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Session["UserName"].ToString()</span>
                <img class="img-profile rounded-circle"
                     src="~/img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="@Url.Action("Perfil","Conta")">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>