GestaoPedidosNotificacao.UI/Controllers/EntidadeTipoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestaoPedidosNotificacao.UI.Entities;

namespace GestaoPedidosNotificacao.UI.Controllers
{
    public class EntidadeTipoesController : AppBaseController
    {
        private GestaoPedidosNotificacaoDBEntities db = new GestaoPedidosNotificacaoDBEntities();

        // GET: EntidadeTipoes
        public ActionResult Index()
        {
            return View(db.EntidadeTipoes.ToList());
        }

        // GET: EntidadeTipoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EntidadeTipo entidadeTipo = db.EntidadeTipoes.Find(id);
            if (entidadeTipo == null)
            {
                return HttpNotFound();
            }
            return View(entidadeTipo);
        }

        // GET: EntidadeTipoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EntidadeTipoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome")] EntidadeTipo entidadeTipo)
        {
            if (ModelState.IsValid)
            {
                db.EntidadeTipoes.Add(entidadeTipo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(entidadeTipo);
        }

        // GET: EntidadeTipoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EntidadeTipo entidadeTipo = db.EntidadeTipoes.Find(id);
            if (entidadeTipo == null)
            {
                return HttpNotFound();
            }
            return View(entidadeTipo);
        }

        // POST: EntidadeTipoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome")] EntidadeTipo entidadeTipo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entidadeTipo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(entidadeTipo);
        }

        // GET: EntidadeTipoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EntidadeTipo entidadeTipo = db.EntidadeTipoes.Find(id);
            if (entidadeTipo == null)
            {
                return HttpNotFound();
            }
            return View(entidadeTipo);
        }

        // POST: EntidadeTipoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EntidadeTipo entidadeTipo = db.EntidadeTipoes.Find(id);
            db.EntidadeTipoes.Remove(entidadeTipo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestaoPedidosNotificacao.UI/Views/EntidadeTipoes/Create.cshtml
@model GestaoPedidosNotificacao.UI.Entities.EntidadeTipo

@{
    ViewBag.Title = "Criar tipo de entidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

GestaoPedidosNotificacao.UI/Views/EntidadeTipoes/Delete.cshtml
@model GestaoPedidosNotificacao.UI.Entities.EntidadeTipo

@{
    ViewBag.Title = "Excluir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Tem certeza de que deseja excluir isso?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> 
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

GestaoPedidosNotificacao.UI/Views/EntidadeTipoes/Details.cshtml
@model GestaoPedidosNotificacao.UI.Entities.EntidadeTipo

@{
    ViewBag.Title = "Tipo de Entidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) 
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
</p>

GestaoPedidosNotificacao.UI/Views/EntidadeTipoes/Edit.cshtml
@model GestaoPedidosNotificacao.UI.Entities.EntidadeTipo

@{
    ViewBag.Title = "Editar tipo de entidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index",null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
    
</div>

GestaoPedidosNotificacao.UI/Views/EntidadeTipoes/Index.cshtml
@model IEnumerable<GestaoPedidosNotificacao.UI.Entities.EntidadeTipo>

@{
    ViewBag.Title = "Tipos de Entidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card mb-4">

    <div class="card-body">
        <span class="float-right">
            <br />
            @Html.ActionLink("Novo Tipo", "Create", null, new { @class = "btn btn-primary" })
            <br />.
        </span>
        <table id="dataTable" class="table table-bordered dataTable" style="width:100%">
            <thead>
                <tr role="row">
                    <th tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="@Html.DisplayNameFor(model => model.Nome): activate to sort column ascending">
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th style="width:200px;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            <a href="@Url.Action("Details","EntidadeTipoes", new { id=item.Id })" class="btn btn-primary btn-circle">
                                <i class="fas fa-search"></i>
                            </a>
                            <a href="@Url.Action("Edit","EntidadeTipoes", new { id=item.Id })" class="btn btn-success btn-circle">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="@Url.Action("Delete","EntidadeTipoes", new { id=item.Id })" class="btn btn-danger btn-circle">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>